techniq/layerchart

src/lib/components/Bar.svelte
src/lib/components/Bars.svelte
src/lib/components/Highlight.svelte
src/routes/_NavMenu.svelte
src/routes/docs/components/Tooltip/+page.svelte
src/routes/docs/components/Tooltip/TooltipControls.svelte
src/routes/docs/examples/Bars/+page.svelte
src/routes/docs/examples/Columns/+page.svelte
src/routes/docs/examples/Columns/+page.ts
src/routes/docs/examples/Sparkbar/+page.svelte
src/routes/docs/examples/Sparkbar/+page.ts
src/routes/docs/examples/Sparkline/+page.ts

This replaces the previous PR #45.
The goal was refactoring Bars.svelte to better handle bar highlights.
I went with keeping the two different props (bar and area) for the Highlight component. This made more sense to me when dealing with examples like the multi-bar example for the Tooltip component.
I was not able to use setContext and getContext because Highlight is a sibling of Bars, not a child. I initially thought it would get the context from the closest sibling, but that is not the case. Therefore if you choose to have non-default values for thins like stroke, radius, and strokeWidth need to be passed in with the bar prop.
Open to feedback on improving this PR.

Bars bar component refactoring

---

src/lib/components/Highlight.svelte
src/routes/_NavMenu.svelte
src/routes/docs/examples/Columns/+page.svelte
src/routes/docs/examples/Columns/+page.ts
src/routes/docs/examples/Sparkbar/+page.svelte
src/routes/docs/examples/Sparkbar/+page.ts
src/routes/docs/examples/Sparkline/+page.ts

Here are some Sparkbar examples. I ran into the situation of the current "area" Highlights not working well for Sparkbars, so I added "bar" highlights. Open to feedback on how this was implemented.

new sparkbar examples and changes to allow bar only highlights

---

packages/layerchart/src/lib/components/Spline.svelte

Minor update, simply explaining how to use the curve prop on Spline component to avoid confusion moving forward (I was the one who was confused lol). 
Making users aware the curve needs to be imported via d3-shape

Add JSDocs Explanation to the Spline Curve Prop

---

.changeset/beige-shrimps-rescue.md
packages/layerchart/src/lib/components/Bar.svelte
packages/layerchart/src/routes/docs/examples/Bars/+page.svelte
packages/layerchart/src/routes/docs/examples/Columns/+page.svelte

[Bar] Add `rounded` prop to round single side (or corner) using path

---

.changeset/five-phones-tease.md
.changeset/itchy-cameras-guess.md
.changeset/pretty-vans-exist.md
.changeset/purple-tools-eat.md
packages/layerchart/src/lib/components/Brush.svelte
packages/layerchart/src/lib/components/ChartClipPath.svelte
packages/layerchart/src/lib/components/Frame.svelte
packages/layerchart/src/lib/components/Group.svelte
packages/layerchart/src/lib/components/Rect.svelte
packages/layerchart/src/lib/components/TooltipContext.svelte
packages/layerchart/src/lib/components/index.ts
packages/layerchart/src/lib/utils/genData.ts
packages/layerchart/src/routes/_NavMenu.svelte
packages/layerchart/src/routes/docs/components/Brush/+page.svelte
packages/layerchart/src/routes/docs/components/Brush/+page.ts

Brush component

---

packages/layerchart/src/lib/components/ForceSimulation.svelte
packages/layerchart/src/routes/docs/examples/Beeswarm/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceDisjointGraph/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceGraph/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceGroup/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceLattice/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceTree/+page.svelte

This admittedly major refactor of `ForceSimulation` resolves #198, #202, #203 and #204, while adding support for highly dynamic, yet efficient simulations.
- Exports `cloneData` as `const` (rather than `let`)
(resolves #203)
- Updates `alpha` prop based on internal d3 simulation (important: dynamic sims now need reheating!)
(resolves #202)
- No longer re-initializes forces on unrelated prop-changes
(resolves #204)
- No longer re-initializes all forces if any of them changes
(resolves #201)
- No longer rebuilds internal `d3.Simulation` for `static=true` on every frame
- Automatically evicts dropped forces
(resolves #206)
- Exports `start`, `tick` and `end` events
(resolves #198)
- Exports `stopped` prop for pausing simulation
- Adds all sorts of controls to "Force Graph" example for …

Refactor `ForceSimulation` to allow for more dynamism

---

.changeset/dry-mugs-nail.md
packages/layerchart/src/lib/components/Highlight.svelte
packages/layerchart/src/routes/docs/examples/AreaStack/+page.svelte

https://github.com/techniq/layerchart/assets/177476/4df0d2cb-bdbf-4edd-ab44-9e09fc2989d8
https://github.com/techniq/layerchart/assets/177476/1b475765-2e5b-400e-a06c-bce8b5e860fd

[Highlight] Support stack data showing individual points and with correct color

---

.changeset/tricky-cats-cheer.md
packages/layerchart/src/lib/components/Highlight.svelte
packages/layerchart/src/routes/docs/examples/Area/+page.svelte

https://github.com/techniq/layerchart/assets/177476/37356f1d-5b8d-411d-8625-7892f32583ea 
https://github.com/techniq/layerchart/assets/177476/d1bc5890-bf8f-452f-92e2-d390390f006f

[Highlight] Support non-stack array accessor when displaying points

---

.github/workflows/build-preview.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy-prod.yml

Saw you were still using node 18.x, and left it as such, but could update if needed.
TODO:

chore: Update deployment scripts

---

packages/layerchart/src/routes/docs/examples/CollisionDetection/+page.svelte

All other examples already are re-using the forces.
I reckon this tiny doc change doesn't require a changeset?

Avoid re-creating/-initializing the many-body force in 'Collision Detection' example

---

.changeset/cyan-hairs-march.md
.changeset/loud-eagles-decide.md
packages/layerchart/src/lib/docs/Preview.svelte

Closed #229
Copying to clipboard will now copy `Date` instances as `new Date('...')` instead of `'...'` to fix type issues when used with `scaleTime()`, etc (common getting started issue on Discord)
```js
[
{
"date": "2024-09-11T04:00:00.000Z",
"value": 70
},
{
"date": "2024-09-12T04:00:00.000Z",
"value": 95
},
// ...
]
```
```js
[
{
"date": new Date('2024-09-11T04:00:00.000Z'),
"value": 70
},
{
"date": new Date('2024-09-12T04:00:00.000Z'),
"value": 95
},
// ...
]
```

docs: Copy `Date` data as `new Date(...)` to clipboard and stringify example data to clipboard on demand

---

.changeset/big-gifts-notice.md
packages/layerchart/src/lib/components/Bar.svelte
packages/layerchart/src/lib/components/Spline.svelte

Try passing a `strokeWidth` prop for a `BarChart`'s `bars` and you'll notice that nothing changes:
```svelte
<BarChart
...
props={{ bars: { strokeWidth: 4 } }}
/>
```
but add `radius: 0` to the mix and suddenly things do change as expected:
```svelte
<BarChart
...
props={{ bars: { radius: 0, strokeWidth: 4 } }}
/>
```
This was due to `Bar` passing its `strokeWidth` prop to `Rect`/`Spline` via `stroke-width={strokeWidth}` (instead of the provided `strokeWidth` props):
```svelte
// Bar.svelte
{#if (_rounded === 'all' || radius === 0) && renderContext === 'svg'}
<Rect
// ...
stroke-width={strokeWidth} // 👈🏻 bug! this should have been just `{strokeWidth}`
// ...
{...$$restProps}
// ...
/>
{:else}
<Spline
// ...
stroke-width={strokeWidth} // 👈🏻 bug! this should have been just `{strokeWidth}` …
```

Fix passing of `strokeWidth` prop from `Bar` to `Rect`/`Spline` components

---

.changeset/swift-dragons-approve.md
packages/layerchart/src/lib/components/charts/AreaChart.svelte
packages/layerchart/src/lib/components/charts/BarChart.svelte
packages/layerchart/src/lib/components/charts/LineChart.svelte
packages/layerchart/src/lib/components/charts/PieChart.svelte
packages/layerchart/src/lib/components/charts/ScatterChart.svelte
packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte

Tooltip item series highlight

---

.changeset/wild-pumas-doubt.md
packages/layerchart/src/lib/components/charts/AreaChart.svelte
packages/layerchart/src/lib/components/charts/BarChart.svelte
packages/layerchart/src/lib/components/charts/LineChart.svelte
packages/layerchart/src/lib/components/charts/PieChart.svelte
packages/layerchart/src/lib/components/charts/ScatterChart.svelte
packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte

Expose `tooltipContext` to enable `bind:` usage for external access

---

.changeset/great-lines-happen.md
packages/layerchart/src/lib/components/Spline.svelte

Toggling between "Single" and "Series" on [wide_data_processed](https://www.layerchart.com/docs/performance/wide_data_processed) perf example saw up to ~33% perf improvement on initial render (using canvas render context but similar for svg)
Before | After
--- | ---
Type | Before | After | Improvement
--- | --- | --- | ---
Single | 118-136ms | 92-126ms | ~7-22%
Series | 286-297ms | 190-238ms | ~20-33%

fix(Spline): Improve initial render performance when tweened disabled (default)

---

.changeset/shy-peaches-talk.md
packages/layerchart/src/lib/components/charts/AreaChart.svelte
packages/layerchart/src/lib/components/charts/BarChart.svelte
packages/layerchart/src/lib/components/charts/LineChart.svelte
packages/layerchart/src/lib/components/charts/PieChart.svelte
packages/layerchart/src/lib/components/charts/ScatterChart.svelte
packages/layerchart/src/lib/components/layout/Canvas.svelte
packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte

Continuing the work of letting users specify props for `svg` and `canvas`. This PR adds `canvas` and `svg` props to allow customization of rendering behavior based on the selected `renderContext`.  
Would appreciate a review to confirm that these are all the necessary places to add support for `canvas` and `svg` props!
Also, I had to cast to `any` to avoid a gnarly TypeScrip error - this may not be the best approach, so open to suggestions for a cleaner solution.

Allow users to specify props for SVG and Canvas

---

.changeset/khaki-owls-argue.md
packages/layerchart/src/lib/components/charts/AreaChart.svelte
packages/layerchart/src/lib/components/charts/BarChart.svelte
packages/layerchart/src/lib/components/charts/LineChart.svelte
packages/layerchart/src/lib/components/charts/ScatterChart.svelte

Reactively rebuild `get_Props()` functions when `highlightSeriesKey` is updated. Fixes Svelte 3/4 reactivity issues when hovering legend, points, etc

---

.changeset/flat-terms-wave.md
packages/layerchart/src/lib/components/Area.svelte
packages/layerchart/src/lib/components/Link.svelte
packages/layerchart/src/lib/components/Spline.svelte
packages/layerchart/src/lib/utils/object.ts
packages/layerchart/src/routes/docs/examples/Pack/+page.svelte
packages/layerchart/src/routes/docs/examples/Sankey/+page.svelte

Fix advertant tweening due to non-granular object reactivity with tweened options

---

.changeset/new-lights-lead.md
packages/layerchart/src/lib/components/tooltip/TooltipContext.svelte

fix(TooltipContext): Properly detect non-manual modes for pointer chart bounds detection

---

.changeset/tiny-buckets-nail.md
packages/layerchart/src/lib/components/charts/AreaChart.svelte
packages/layerchart/src/lib/components/charts/LineChart.svelte

fix(AreaChart|LineChart): Hide highlight points when set to `false`

---

.changeset/proud-fans-rush.md
packages/layerchart/src/lib/components/tooltip/TooltipContext.svelte

fix(TooltipContext): Ignore clicks without data (triggered from Legend clicks, for example).  Fixes #443

---

packages/layerchart/package.json
pnpm-lock.yaml

Fix: https://github.com/techniq/layerchart/issues/452

(rmv) shapefile & topojson-client from deps. It's now only in devDeps

---

packages/layerchart/src/lib/utils/array.ts
packages/layerchart/src/lib/utils/stack.ts

Fixing this message: 
`
"stackOrderNone" is imported from external module "d3-shape" but never used in "src/routes/app/dashboard/+page.svelte", "../../node_modules/.pnpm/layerchart@1.0.7_svelte@5.23.0_ts-node@10.9.1_@types+node@22.13.1_typescript@5.8.2__typescript@5.8.2/node_modules/layerchart/dist/utils/stack.js", "../../node_modules/.pnpm/layerchart@1.0.7_svelte@5.23.0_ts-node@10.9.1_@types+node@22.13.1_typescript@5.8.2__typescript@5.8.2/node_modules/layerchart/dist/components/GeoPath.svelte", "../../node_modules/.pnpm/layerchart@1.0.7_svelte@5.23.0_ts-node@10.9.1_@types+node@22.13.1_typescript@5.8.2__typescript@5.8.2/node_modules/layerchart/dist/components/GeoSpline.svelte", "../../node_modules/.pnpm/layercake@8.4.2_svelte@5.23.0_typescript@5.8.2/node_modules/layercake/dist/lib/stack.js …

help treeshaking imports

---

packages/layerchart/src/routes/getting-started/+page.svelte

Hi,
Updating URL to svelte CLI instead of deprecated `svelte-add`

docs: update svelte CLI url

---

.changeset/kind-jokes-laugh.md
packages/layerchart/src/lib/components/Spline.svelte

fix(Spline): Do not unnecessarily render mid/end markers. Fixes Firefox when used with ClipPath.

---

.changeset/lazy-taxis-hang.md
packages/layerchart/src/lib/components/charts/BarChart.svelte

feat(BarChart): Pass derived scales (x1, y1) to slots props. Useful for custom labels with group series layout

---

.changeset/eighty-islands-jam.md
packages/layerchart/src/lib/components/Axis.svelte
packages/layerchart/src/lib/components/Bars.svelte
packages/layerchart/src/lib/components/Blur.svelte
packages/layerchart/src/lib/components/ClipPath.svelte
packages/layerchart/src/lib/components/GeoEdgeFade.svelte
packages/layerchart/src/lib/components/Graticule.svelte
packages/layerchart/src/lib/components/Grid.svelte
packages/layerchart/src/lib/components/Group.svelte
packages/layerchart/src/lib/components/Hull.svelte
packages/layerchart/src/lib/components/Labels.svelte
packages/layerchart/src/lib/components/Rule.svelte
packages/layerchart/src/lib/components/Voronoi.svelte
packages/layerchart/src/routes/_NavMenu.svelte
packages/layerchart/src/routes/docs/performance/dimension_arrays/+page.svelte
packages/layerchart/src/routes/docs/performance/dimension_arrays_processed/+page.svelte
packages/layerchart/src/routes/docs/performance/series_arrays/+page.svelte
packages/layerchart/src/routes/docs/performance/streaming/+page.svelte
packages/layerchart/src/routes/docs/performance/wide_data/+page.svelte
packages/layerchart/src/routes/docs/performance/wide_data_processed/+page.svelte

See related [thread](https://discord.com/channels/920755200552226868/1369691058933334016) for more context.
Profiling the new [streaming](https://techniq-performance-eval.layerchart.pages.dev/docs/performance/streaming) performance example, you'll notice a memory leak while it's running.  If you stop running (and await a little while) or manually trigger a GC, most (but not all) of the memory will be recovered.  Grabbing a heap snapshot after GC'ing still shows a lot of detached elements, especially SVG `<g>` elements, comments, and text.
I thought the main culprit might be the canvas [getComputedStyles()](https://github.com/techniq/layerchart/blob/next/packages/layerchart/src/lib/utils/canvas.ts#L24-L39) util that creates a `<svg>` element to resolve CSS classes and variables, but the …

Streaming performance investigation

---

.changeset/social-masks-teach.md
packages/layerchart/src/lib/utils/ticks.ts

fix(Axis): Fix multiline month when day tick does not align on first of month

---

.changeset/crazy-friends-talk.md
packages/layerchart/src/lib/components/ForceSimulation.svelte
packages/layerchart/src/routes/docs/examples/CollisionDetection/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceDisjointGraph/+page.svelte
packages/layerchart/src/routes/docs/examples/ForceGraph/+page.svelte

(This PR is stacked on top of https://github.com/techniq/layerchart/pull/526.)
I also added `links` to the arguments of `ForceSimulation`'s `children` snippet, since the user-stored `links` are merely `links: LinkDatum[]`, but the snippet-provided ones are `links: (LinkDatum & SimulationLinkDatum<LinkNode & SimulationNodeDatum>)[]`, i.e. they provide access to the simulation-specific fields.
Check out the commit _before_ the one named "Expose links via children snippet of ForceSimulation" to check out the breakage that you get without exposing `links`.
That said having `ForceSimulation` generic over `Node` and `Link` is quite nice as it means that e.g. the `simulation` passed to its `children` snippet is properly typed already.

Make `ForceSimulation` generic over its nodes and links, i.e. `ForceSimulation<Node, Link>`

---

packages/layerchart/src/routes/docs/+layout.svelte

Based off issue #532.
Simplified Charts (LineChart, BarChart, ArcChart, ...) are located in `components/charts/...Chart.svelte`, but docs still reference them at `components/...Chart.svelte`. Same for Tooltip and TooltipContext (they are located at `components/tooltip/...`). 
ArcChart doesn't yet exist in `main` branch, so it's important to change blob/main links to blob/next, otherwise it will be broken, too. (as well as implementations shown on the page won't match what's at github link)
Implemented a small lookup function (`getComponentPath` at `+layout.svelte`) to correctly map component names to their nested folder paths and updated branch reference to `next` both at `Page Source` and `Source` button href's.

Fix source links for `Simplified Charts` and `Tooltip` in docs; Use blob/next instead of blob/main for links.

---

.changeset/slow-hounds-hide.md
packages/layerchart/src/lib/components/ForceSimulation.svelte

This makes it easier to customize force simulations without having to rely on what currently are internal details (that merely get a mention in the docs, making them semi-public).

Expose `ForceSimulation`'s default values by exporting them as constants

---

.changeset/cruel-rats-taste.md
packages/layerchart/src/lib/components/Spline.svelte
packages/layerchart/src/routes/docs/components/Spline/+page.svelte

feat(Spline): Add `value` prop to startContent/endContent snippets

---

.changeset/khaki-pugs-hammer.md
packages/layerchart/src/lib/components/ForceSimulation.svelte

I discovered the bug while experimenting with an approach of adjusting the `alphaTarget`/`alphaDecay` dynamically, based on the simulation's total kinetic energy (i.e. sum of node velocities): the simulation just kept running, despite `alpha` having dropped far, far below `0.001` already.
Any change to `alphaTarget`/`alphaDecay` caused the simulation to get restarted, even if `alpha` had already fallen below `alphaMin`.
There are a couple of places where `runOrResumeSimulation();` gets called, but currently only one of them is guarded by a `alpha >= alphaMin` check, so I move the check into `runOrResumeSimulation()` itself.
The bug is trivially reproducible by doing something like this:
```typescript
function handleTick(e: { alpha: number; alphaTarget: number }) {
// the re-fires the …
```

fix(force-simulation): Fix a bug that would sometimes keep a simulation running indefinitely

---

.changeset/old-lions-hide.md
packages/layerchart/src/lib/components/Axis.svelte

Still seeing some memory leak / DOM node increase (#585), but using `date.valueOf()` instead of `date` instances for `{#each}` keys greatly reduces the issue.  `{#each}` [docs](https://svelte.dev/docs/svelte/each#Keyed-each-blocks) state 
> The key can be any object, but strings and numbers are recommended since they allow identity to persist when the objects themselves change.
After 30s, `71,027` DOM nodes, `231MB` JS heap size
https://github.com/user-attachments/assets/fcff9088-2af0-40b2-a9a8-61d78e1ee483
After 30s, `7,009` DOM nodes, `142MB` JS heap size
https://github.com/user-attachments/assets/8553e0c5-4c40-425b-a221-9cb3aa66ea9f

fix(Axis): Fix memory leak and improve performance when tick values are `Date` instances

---

.changeset/lemon-bats-change.md
packages/layerchart/src/lib/components/ForceSimulation.svelte

While working on a "newly added nodes get pre-positioned to the average position of their already-existing neighbors" feature for a graph (but the same would apply to pretty much any other imaginable pre-positioning scheme) I found that I needed a callback that would allow me to perform such pre-positioning whenever the nodes of the simulation change (that is the actual set of nodes, not merely their positions), but before the simulation has had a chance to touch the nodes (as that would result in the default behavior of positioning nodes around the origin):
```typescript
function handleNodesChange(
event: OnNodesChangeEvent<NodeDatum, LinkDatum | undefined>
) {
positionUninitializedNodesAtCentroidOfNeighborhood(
event.nodes,
event.links as LinkDatum[],
(node) => node.id
);
}
```
```html …
```

Add `onNodesChange` callback to `ForceSimulation`
