- src/routes/docs/components/Tooltip/+page.svelte
> add yDomain in order to set ordering now that Layer Cake auto sorts

- .changeset/lucky-plums-tie.md
- packages/layerchart/src/lib/components/Tooltip.svelte
- packages/layerchart/src/lib/components/TooltipContext.svelte
- packages/layerchart/src/routes/docs/components/Tooltip/+page.svelte
- packages/layerchart/src/routes/docs/examples/Area/+page.svelte
- packages/layerchart/src/routes/docs/examples/GeoPath/+page.svelte
- packages/layerchart/src/routes/docs/examples/GeoTile/+page.svelte
- packages/layerchart/src/routes/docs/examples/Sparkbar/+page.svelte
- packages/layerchart/src/routes/docs/examples/Sparkline/+page.svelte
- packages/layerchart/src/routes/docs/examples/ZoomableTileMap/+page.svelte
> Tooltip position improvements

- .changeset/little-rabbits-yell.md
- packages/layerchart/src/lib/components/Area.svelte
- packages/layerchart/src/lib/components/AreaStack.svelte
- packages/layerchart/src/lib/components/Spline.svelte
- packages/layerchart/src/lib/components/TooltipContext.svelte
- packages/layerchart/src/routes/docs/examples/Line/+page.svelte
- packages/layerchart/src/routes/docs/examples/RadialLine/+page.svelte
> [Area/AreaStack/Spline] Simplify overwriting x/y accessors by applying xScale/yScale within components

- .changeset/hot-ladybugs-battle.md
- packages/layerchart/src/lib/components/Area.svelte
- packages/layerchart/src/lib/components/AreaStack.svelte
- packages/layerchart/src/routes/docs/examples/AreaStack/+page.svelte
> [AreaStack] Support passing slot for custom <Area> (enabling modifications in including <LinearGradient> fill)

- .changeset/nine-pillows-ring.md
- packages/layerchart/src/lib/components/index.ts
It is nicer to be able to use the already implemented Bar component inside the `Bars` slot.
See more at https://discord.com/channels/920755200552226868/1168230758276677762/1228256447834492988
> Export the individual Bar component

- packages/layerchart/src/routes/docs/examples/Oscilloscope/+page.svelte
Otherwise it holds on to it until the tab is closed. It still seems to take 10-15 seconds for the recording icon in the browser tab to go away.
> Oscilloscope example: release the AudioContext and stop calling `step` when leaving the page

- .changeset/cyan-ghosts-sort.md
- .changeset/sixty-jars-punch.md
- packages/layerchart/src/lib/components/Axis.svelte
- packages/layerchart/src/routes/docs/components/Axis/+page.svelte
- packages/layerchart/src/routes/docs/examples/Area/+page.svelte
- packages/layerchart/src/routes/docs/examples/Histogram/+page.svelte
[Axis] Rename `labelProps` to `tickLabelProps` and `label` slot to `tickLabel`
[Axis] Add label support. Resolves issue #100
> [Axis] Add label support

- .changeset/strange-phones-dream.md
- packages/layerchart/src/lib/components/RadialGradient.svelte
- packages/layerchart/src/lib/components/index.ts
- packages/layerchart/src/routes/_NavMenu.svelte
- packages/layerchart/src/routes/docs/components/LinearGradient/+page.svelte
- packages/layerchart/src/routes/docs/components/LinearGradient/+page.ts
- packages/layerchart/src/routes/docs/components/Pattern/+page.ts
- packages/layerchart/src/routes/docs/components/RadialGradient/+page.svelte
- packages/layerchart/src/routes/docs/components/RadialGradient/+page.ts
> Add RadialGradient component

- .changeset/chatty-years-sin.md
- .changeset/chilly-carpets-juggle.md
- .changeset/dull-keys-camp.md
- .changeset/empty-baboons-wonder.md
- .changeset/fuzzy-points-work.md
- .changeset/nice-apes-jump.md
- .changeset/rotten-dolphins-wave.md
- .changeset/rude-moose-cross.md
- .changeset/sweet-singers-dream.md
- .changeset/thirty-parrots-kiss.md
- packages/layerchart/src/lib/components/Axis.svelte
- packages/layerchart/src/lib/components/Labels.svelte
- packages/layerchart/src/lib/components/Legend.svelte
- packages/layerchart/src/lib/components/Points.svelte
- packages/layerchart/src/lib/components/Rule.svelte
- packages/layerchart/src/lib/components/charts/AreaChart.svelte
- packages/layerchart/src/lib/components/charts/BarChart.svelte
- packages/layerchart/src/lib/components/charts/LineChart.svelte
- packages/layerchart/src/lib/components/charts/PieChart.svelte
- packages/layerchart/src/lib/components/charts/ScatterChart.svelte
- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
- packages/layerchart/src/routes/docs/components/Axis/+page.svelte
- packages/layerchart/src/routes/docs/components/BarChart/+page.svelte
- packages/layerchart/src/routes/docs/components/Legend/+page.svelte
- packages/layerchart/src/routes/docs/components/LineChart/+page.svelte
- packages/layerchart/src/routes/docs/components/PieChart/+page.svelte
- packages/layerchart/src/routes/docs/components/ScatterChart/+page.svelte
> Simplified Charts improvements

- packages/layerchart/src/lib/components/Chart.svelte
- packages/layerchart/src/lib/components/ChartContext.svelte
Just some small typos I stumbled upon while spelunking.
None of these fixes have any effect on the code, nor do they appear anywhere user-observable.
Hence no change-set for now. Lemme know though, if you'd still prefer one.
> Fix a few typos

- .changeset/rotten-radios-tell.md
- .changeset/warm-flowers-sniff.md
- packages/layerchart/src/lib/components/Brush.svelte
- packages/layerchart/src/routes/docs/components/Brush/+page.svelte
> feat(Brush): Add `labels` support

- .changeset/eleven-bears-repeat.md
- .changeset/hungry-hounds-melt.md
- packages/layerchart/src/lib/components/Line.svelte
- packages/layerchart/src/lib/components/Link.svelte
- packages/layerchart/src/lib/components/Marker.svelte
- packages/layerchart/src/lib/components/Spline.svelte
- packages/layerchart/src/routes/_NavMenu.svelte
- packages/layerchart/src/routes/docs/components/Axis/+page.svelte
- packages/layerchart/src/routes/docs/components/Line/+page.svelte
- packages/layerchart/src/routes/docs/components/Marker/+page.svelte
- packages/layerchart/src/routes/docs/components/Marker/+page.ts
- packages/layerchart/src/routes/docs/components/Spline/+page.svelte
> feat: Add Markers component

- .changeset/chatty-apes-wink.md
- .changeset/cuddly-poems-prove.md
- .changeset/lazy-weeks-dance.md
- .changeset/pretty-taxis-sin.md
- .changeset/real-shrimps-attend.md
- .changeset/shaggy-cameras-double.md
- packages/layerchart/src/lib/components/Bars.svelte
- packages/layerchart/src/lib/components/Highlight.svelte
- packages/layerchart/src/lib/components/charts/AreaChart.svelte
- packages/layerchart/src/lib/components/charts/BarChart.svelte
- packages/layerchart/src/lib/components/charts/LineChart.svelte
- packages/layerchart/src/lib/components/charts/PieChart.svelte
- packages/layerchart/src/lib/components/charts/ScatterChart.svelte
- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
- packages/layerchart/src/routes/docs/components/BarChart/+page.svelte
- packages/layerchart/src/routes/docs/components/LineChart/+page.svelte
- packages/layerchart/src/routes/docs/components/PieChart/+page.svelte
- packages/layerchart/src/routes/docs/components/ScatterChart/+page.svelte
- packages/layerchart/src/routes/docs/components/Tooltip/+page.svelte
> Simplified chart click event / callbacks

- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
> docs(AreaChart): Add funnel example

- .changeset/honest-nails-brush.md
- .changeset/moody-chefs-buy.md
- .changeset/nice-cats-joke.md
- .changeset/pink-mangos-flash.md
- .changeset/poor-shoes-refuse.md
- .changeset/two-cats-fly.md
- .changeset/warm-icons-sleep.md
- packages/layerchart/src/lib/components/Area.svelte
- packages/layerchart/src/lib/components/Circle.svelte
- packages/layerchart/src/lib/components/Highlight.svelte
- packages/layerchart/src/lib/components/Legend.svelte
- packages/layerchart/src/lib/components/Spline.svelte
- packages/layerchart/src/lib/components/charts/AreaChart.svelte
- packages/layerchart/src/lib/components/charts/BarChart.svelte
- packages/layerchart/src/lib/components/charts/LineChart.svelte
- packages/layerchart/src/lib/components/charts/PieChart.svelte
- packages/layerchart/src/lib/components/charts/ScatterChart.svelte
- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
- packages/layerchart/src/routes/docs/components/BarChart/+page.svelte
- packages/layerchart/src/routes/docs/components/LineChart/+page.svelte
- packages/layerchart/src/routes/docs/components/PieChart/+page.svelte
- packages/layerchart/src/routes/docs/components/ScatterChart/+page.svelte
> Legend and highlight series integration

- .changeset/long-seas-invent.md
- .changeset/mighty-toes-teach.md
- .changeset/perfect-eagles-build.md
- packages/layerchart/src/lib/components/charts/AreaChart.svelte
- packages/layerchart/src/lib/components/charts/BarChart.svelte
- packages/layerchart/src/lib/components/charts/LineChart.svelte
- packages/layerchart/src/lib/components/charts/ScatterChart.svelte
- packages/layerchart/src/lib/components/tooltip/Tooltip.svelte
- packages/layerchart/src/lib/components/tooltip/TooltipContext.svelte
- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
> Lockable and interactive tooltips

- .changeset/hot-beers-admire.md
- .changeset/many-clouds-whisper.md
- .changeset/tame-brooms-bake.md
- packages/layerchart/src/lib/components/charts/AreaChart.svelte
- packages/layerchart/src/lib/components/charts/BarChart.svelte
- packages/layerchart/src/lib/components/charts/LineChart.svelte
- packages/layerchart/src/lib/components/charts/ScatterChart.svelte
- packages/layerchart/src/lib/components/tooltip/TooltipHeader.svelte
- packages/layerchart/src/routes/docs/components/BarChart/+page.svelte
- packages/layerchart/src/routes/docs/performance/dimension_arrays/+page.svelte
- packages/layerchart/src/routes/docs/performance/dimension_arrays_processed/+page.svelte
- packages/layerchart/src/routes/docs/performance/series_arrays/+page.svelte
- packages/layerchart/src/routes/docs/performance/wide_data/+page.svelte
> Tooltip header format

- .changeset/dull-radios-crash.md
- .changeset/selfish-hats-fry.md
- .changeset/silly-wasps-allow.md
- .changeset/three-squids-count.md
- packages/layerchart/src/lib/components/Arc.svelte
- packages/layerchart/src/lib/components/Area.svelte
- packages/layerchart/src/lib/components/Circle.svelte
- packages/layerchart/src/lib/components/GeoPath.svelte
- packages/layerchart/src/lib/components/GeoTile.svelte
- packages/layerchart/src/lib/components/Group.svelte
- packages/layerchart/src/lib/components/Line.svelte
- packages/layerchart/src/lib/components/LinearGradient.svelte
- packages/layerchart/src/lib/components/RadialGradient.svelte
- packages/layerchart/src/lib/components/Rect.svelte
- packages/layerchart/src/lib/components/Spline.svelte
- packages/layerchart/src/lib/components/Text.svelte
- packages/layerchart/src/lib/utils/canvas.ts
> Improve canvas style/class reactivity

- .changeset/bright-kings-wave.md
- .changeset/chatty-adults-shop.md
- .changeset/hungry-geckos-relate.md
- .changeset/rotten-yaks-marry.md
- .changeset/tidy-humans-divide.md
- packages/layerchart/src/lib/components/Brush.svelte
- packages/layerchart/src/lib/components/ChartClipPath.svelte
- packages/layerchart/src/lib/components/CircleClipPath.svelte
- packages/layerchart/src/lib/components/RectClipPath.svelte
- packages/layerchart/src/lib/components/charts/AreaChart.svelte
- packages/layerchart/src/lib/components/charts/BarChart.svelte
- packages/layerchart/src/lib/components/charts/LineChart.svelte
- packages/layerchart/src/lib/components/charts/PieChart.svelte
- packages/layerchart/src/lib/components/charts/ScatterChart.svelte
- packages/layerchart/src/lib/utils/types.ts
- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
- packages/layerchart/src/routes/docs/components/LineChart/+page.svelte
- packages/layerchart/src/routes/docs/components/ScatterChart/+page.svelte
> Brush integration

- .changeset/chilled-files-poke.md
- packages/layerchart/package.json
- packages/layerchart/src/lib/components/tooltip/TooltipContext.svelte
- packages/layerchart/src/routes/docs/components/AreaChart/+page.svelte
- packages/layerchart/src/routes/docs/components/Tooltip/+page.ts
- pnpm-lock.yaml
- Added `hideDelay` prop to Tooltip for configurable hide behavior
- Prevents accidental tooltip hiding when moving to tooltip content
- Allows smooth transitions between elements
- Defaults to 0ms with optional delay configuration
> add hideDelay prop to Tooltip

- .github/workflows/pkg-pr-new.yml
> Setup pkg-pr-new to publish npm packages for each pull request

- .changeset/tame-clowns-fetch.md
- packages/layerchart/src/lib/components/tooltip/TooltipContext.svelte
- packages/layerchart/src/routes/docs/components/LineChart/+page.svelte
> Simple annotations

- .changeset/curly-humans-flow.md
- packages/layerchart/src/lib/components/Points.svelte
- packages/layerchart/src/routes/docs/examples/DotPlot/+page.svelte
> fix(Points): Support coloring lines using color `c` scale

- .changeset/dry-mirrors-eat.md
- packages/layerchart/src/lib/components/Area.svelte
> Improve Area `defaultPathData`

- .changeset/smart-dots-rule.md
- packages/layerchart/src/lib/components/Chart.svelte
- packages/layerchart/src/lib/components/Spline.svelte
- packages/layerchart/src/routes/docs/components/LineChart/+page.svelte
> fix(Spline): Only re-draw on data/path changes and not other context (such as width/height)

- .changeset/clear-points-care.md
- packages/layerchart/src/lib/components/tooltip/TooltipContext.svelte
fix #255
https://github.com/user-attachments/assets/f0ffa9c1-4832-4791-9f29-22f40022b9f8
https://github.com/user-attachments/assets/1f7d9d78-974d-4147-9071-915a8efe05a0
> fix(TooltipContext): Fix touch scrolling on mobile. Fixes #255
